. ~/.git-prompt.sh

GIT_PS1_SHOWUPSTREAM="auto"
GIT_PS1_SHOWCONFLICSTATE="yes"
GIT_PS1_SHOWDIRTYSTATE="true"
GIT_PS1_SHOWSTASHSTATE="yes"
GIT_PS1_SHOWUNTRACKEDFILES="yes"
GIT_PS1_SHOWCOLORHINTS="yes"
